Name:           ros-indigo-neo-base-mp-500
Version:        0.1.2
Release:        1%{?dist}
Summary:        ROS neo_base_mp_500 package

Group:          Development/Libraries
License:        BSD
URL:            http://www.neobotix-robots.com
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-cob-sick-s300
Requires:       ros-indigo-neo-platformctrl-diff
Requires:       ros-indigo-neo-relayboard
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cob-sick-s300
BuildRequires:  ros-indigo-neo-platformctrl-diff
BuildRequires:  ros-indigo-neo-relayboard

%description
launchfiles for MP_500

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Neobotix <nieland@neobotix.de> - 0.1.2-1
- Autogenerated by Bloom

